##146.155.0.0 a 146.155.255.255

security:
    encoders:
        GanttBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            anonymous: ~
            logout:
                invalidate_session: true
                path:   /logout
                target: /
            #form_login:
                #login_path: /login
                #check_path: /login_check
            simple_form:
                authenticator: multi_authenticator
                check_path: /login_check
                login_path: /login
            switch_user: {role: ROLE_ADMIN, parameter: impersonate}

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, roles: [ROLE_ADMIN, ROLE_OTHER] }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 122.0.0.1 }
        - { path: ^/$, roles: ROLE_OTHER }

    providers:
        our_db_provider:
            entity:
                class: GanttBundle:User
                property: email
                # if you're using multiple entity managers
                # manager_name: customer
