<?php

namespace GanttBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenciaRepository extends EntityRepository
{
}
