<?php

namespace GanttBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HitoRepository extends EntityRepository
{
}
